---
- name: Install tools
  hosts: localhost
  connection: local
  roles:
    - role: indigo-dc.galaxycloud-tools
      galaxy_flavor: 'galaxy-TESTING'
      move_datasets: false
      create_bootstrap_user: true
      galaxy_admin_api_key: 'api_key'
      when: galaxy_flavor != 'galaxy-no-tools'

    - role: indigo-dc.galaxycloud-tooldeps
